const { RELEASE_RULES, CHANGELOG_TYPES } = require('./release.rules.cjs');

module.exports = {
    // You can find out more about the configuration of this file here https://semantic-release.gitbook.io/semantic-release/usage/configuration
    "branches": [
        { "name": 'master' },
        { "name": 'release/*', "prerelease": 'rc' },
        { "name": 'hotfix/*', "prerelease": 'hotfix' },
        { "name": 'develop', "prerelease": 'alpha' },
        { "name": '+([0-9]).x/master', "range": '${name.match(/^(\\d+)\\.x/)[1]}.x' },
        { "name": '+([0-9]).x/release/*', "prerelease": '${name.match(/^(\\d+)\\.x/)[1]}x-rc' },
        { "name": '+([0-9]).x/hotfix/*', "prerelease": '${name.match(/^(\\d+)\\.x/)[1]}x-holfix' },
        { "name": '+([0-9]).x/develop', "prerelease": '${name.match(/^(\\d+)\\.x/)[1]}x-alpha' },
    ],
    "tagFormat": '${version}',
    // Plugins https://semantic-release.gitbook.io/semantic-release/extending/plugins-list
    "plugins": [
        [
            // Analyzes commits and determines which release version should be released.
            '@semantic-release/commit-analyzer',
            {
                "preset": 'conventionalcommits',
                // Define the commits that will increase the release version
                "releaseRules": RELEASE_RULES,
            },
        ],
        [
            // Add release notes
            '@semantic-release/release-notes-generator',
            {
                "preset": 'conventionalcommits',
                // Define the commits that will be described in the release notes
                "presetConfig": { "types": CHANGELOG_TYPES },
            },
        ],
        [
            // Writing release notes to a changelog
            '@semantic-release/changelog',
            { 
                "changelogTitle": "# Changelog",
                "changelogFile": 'CHANGELOG.md' 
            },
        ],
        // A custom plugin necessary for converting custom version identifiers (for example, `N.N.N-1x-alpha.N`) 
        // into the appropriate semver format (for example, `N.N.N-alpha.N`) so that when a version is saved 
        // in `pyproject.toml`, Poetry can convert it to the PEP 440 format (for example, `aN`)
        {
            prepare: async (pluginConfig, context) => {
                process.env.PEP440_VERSION = normalizeToSemver(context.nextRelease.version);
            },
        },
        [
            // Bumping version in pyproject.toml and build .whl
            '@semantic-release/exec',
            {
                "prepareCmd": 'poetry version "$PEP440_VERSION" && poetry build',
            }
        ],
        [
            // Plugin for commits changes
            '@semantic-release/git',
            {
                "assets": ['CHANGELOG.md', 'pyproject.toml'],
                "message":
                    'chore(release): ${nextRelease.version}\n\n' +
                    'Automatically generated by semantic-release'
            },
        ],
        [
            // Release to Github with builded files 
            '@semantic-release/github', 
            {
                "assets": [
                    { "path": 'dist/*' }
                ],
            }
        ],
    ],
};

function normalizeToSemver(version) {
    const [base, ...rest] = version.split('-');

    if (rest.length === 0)
        return version;

    const identifier = rest.join('-');

    const hotfixMatch = identifier.match(/^hotfix\.(\d+)$/);
    if (hotfixMatch) {
        const [, num] = hotfixMatch;
        return `${base}-rc.${num}`;
    }

    const match = identifier.match(/^\d+x-(alpha|rc|hotfix)\.(\d+)$/);

    if (!match)
        return version;

    const [, phase, num] = match;
    const normalizedPhase = phase === 'hotfix' ? 'rc' : phase;

    return `${base}-${normalizedPhase}.${num}`;
}